apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstorepetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstorepetservice
  template:
    metadata:
      labels:
        app: aks-petstorepetservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: petstoreservice
        image: azurepetstorecr.azurecr.io/petstorepetservice:latest
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080
        env:
          - name: PETSTOREPETSERVICE_SERVER_PORT
            value: "80"
          - name: spring.config.name
            value: application_with_everything_enabled
          - name: PETSTORESERVICES_AI_INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: aisecretkey
                key: secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aks-petstorepetservice-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-petstorepetservice
  targetCPUUtilizationPercentage: 80 # target CPU utilization
